services:
  dingus:
    build:
      context: .
      dockerfile: Dockerfile.dingus
      args:
        UID: ${UID}
        GID: ${GID}
    ports:
      - "${FASTAPI_PORT:-8000}:8000"
    container_name: dingus
    volumes:
      - ./src:/src
      - ./data:/data
      - ./logs:/logs
      - ./assets:/assets
      - ./scripts:/scripts
    environment:
      - FASTAPI_PORT=8000
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - CHAT_API_URL=$CHAT_API_URL

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
      args:
        UID: ${UID}
        GID: ${GID}
    ports:
      - "${STREAMLIT_PORT:-8501}:8501"
    container_name: frontend
    volumes:
      - ./frontend/src:/src
      - ./data:/data
      - ./logs:/logs
      - ./assets:/assets
      - ./scripts:/scripts
    environment:
      - STREAMLIT_PORT=8501
      - CHAT_API_URL=$CHAT_API_URL
