name: Code Checks

on:
  pull_request:
    branches:
      - main

jobs:
  code-checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Start Docker Compose Services
        run: |
          docker compose up --build -d
          docker ps  # Debugging: list running containers

      - name: Run Code Checks
        run: |
          docker compose exec -T dingus format-checks
          docker compose exec -T dingus code-checks

      - name: Stop Docker Compose
        if: always()
        run: docker compose down
