name: Code Checks

on:
  pull_request:
    branches:
      - main

env:
  TARGET: build-agent

jobs:
  code-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Create .env
        run: cp sample.env .env
        run: echo "TARGET=build-agent" >> .env

      - name: Start Docker Compose Services
        run: |
          docker compose build --build-arg TARGET=build-agent
          docker ps  # Debugging: list running containers

      - name: Run Code Checks
        run: |
          docker compose exec -T dingus code-checks
          docker compose exec -T frontend code-checks

      - name: Stop Docker Compose
        if: always()
        run: docker compose down
